### ISSUE TITLE
Unexpected JDWP Error: 35

### ISSUE THREAD

**Issue by provegard** [provegard/ncdbg#21]
```
Failed to handle event com.sun.tools.jdi.EventSetImpl$BreakpointEventImpl
com.sun.jdi.InternalException: Unexpected JDWP Error: 35
        at com.sun.tools.jdi.JDWPException.toJDIException(JDWPException.java:65)
        at com.sun.tools.jdi.StackFrameImpl.getValues(StackFrameImpl.java:241)
        at com.programmaticallyspeaking.ncd.nashorn.NashornDebuggerHost.$anonfun$handleBreakpoint$1(NashornDebuggerHost.scala:719)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1406)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at com.programmaticallyspeaking.ncd.nashorn.NashornDebuggerHost.handleBreakpoint(NashornDebuggerHost.scala:715)
        at com.programmaticallyspeaking.ncd.nashorn.NashornDebuggerHost.$anonfun$handleOperation$3(NashornDebuggerHost.scala:398)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1406)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at com.programmaticallyspeaking.ncd.nashorn.NashornDebuggerHost.handleOperation(NashornDebuggerHost.scala:385)
        at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at akka.actor.TypedActor$MethodCall.apply(TypedActor.scala:145)
        at akka.actor.TypedActor$TypedActor$$anonfun$receive$1.$anonfun$applyOrElse$1(TypedActor.scala:310)
        at akka.actor.TypedActor$TypedActor.withContext(TypedActor.scala:298)
        at akka.actor.TypedActor$TypedActor$$anonfun$receive$1.applyOrElse(TypedActor.scala:306)
        at akka.actor.Actor.aroundReceive(Actor.scala:497)
        at akka.actor.Actor.aroundReceive$(Actor.scala:495)
        at akka.actor.TypedActor$TypedActor.aroundReceive(TypedActor.scala:245)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by provegard** [comment]
Error 35 is INVALID_SLOT
