### ISSUE TITLE
Assigning to a local variable via the Scope pane fails

### ISSUE THREAD

**Issue by provegard** [provegard/ncdbg#46]
```
Failed to update the value of z for {"id":"$$locals-ndsf19"} to instance of java.lang.Integer(id=3047)
com.sun.jdi.InvalidTypeException: Can't assign object value to primitive
	at com.sun.tools.jdi.ObjectReferenceImpl.validateAssignment(ObjectReferenceImpl.java:597)
	at com.sun.tools.jdi.ObjectReferenceImpl.prepareForAssignmentTo(ObjectReferenceImpl.java:581)
	at com.sun.tools.jdi.ValueImpl.prepareForAssignment(ValueImpl.java:48)
	at com.sun.tools.jdi.StackFrameImpl.setValue(StackFrameImpl.java:274)
	at com.programmaticallyspeaking.ncd.nashorn.NashornDebuggerHost.$anonfun$updateChangedLocals$7(NashornDebuggerHost.scala:1285)
	at com.programmaticallyspeaking.ncd.nashorn.NashornDebuggerHost.$anonfun$updateChangedLocals$7$adapted(NashornDebuggerHost.scala:1285)
	at scala.Option.foreach(Option.scala:257)
	at com.programmaticallyspeaking.ncd.nashorn.NashornDebuggerHost.$anonfun$updateChangedLocals$6(NashornDebuggerHost.scala:1285)
	at com.programmaticallyspeaking.ncd.nashorn.NashornDebuggerHost.$anonfun$updateChangedLocals$6$adapted(NashornDebuggerHost.scala:1285)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at com.programmaticallyspeaking.ncd.nashorn.NashornDebuggerHost.$anonfun$updateChangedLocals$4(NashornDebuggerHost.scala:1285)
	at com.programmaticallyspeaking.ncd.nashorn.NashornDebuggerHost.$anonfun$updateChangedLocals$4$adapted(NashornDebuggerHost.scala:1282)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1406)
	at com.programmaticallyspeaking.ncd.nashorn.NashornDebuggerHost.$anonfun$updateChangedLocals$3(NashornDebuggerHost.scala:1282)
	at com.programmaticallyspeaking.ncd.nashorn.NashornDebuggerHost.$anonfun$updateChangedLocals$3$adapted(NashornDebuggerHost.scala:1271)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at com.programmaticallyspeaking.ncd.nashorn.NashornDebuggerHost.updateChangedLocals(NashornDebuggerHost.scala:1271)
	at com.programmaticallyspeaking.ncd.nashorn.NashornDebuggerHost.evaluateOnStackFrame(NashornDebuggerHost.scala:1235)
	at com.programmaticallyspeaking.ncd.nashorn.NashornDebuggerHost.$anonfun$evaluateOnStackFrame$3(NashornDebuggerHost.scala:1246)
	at scala.util.Try$.apply(Try.scala:209)
	at com.programmaticallyspeaking.ncd.nashorn.NashornDebuggerHost.evaluateOnStackFrame(NashornDebuggerHost.scala:1245)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.programmaticallyspeaking.ncd.infra.ExecutorProxy$Handler.$anonfun$invoke$2(ExecutorProxy.scala:29)
	at scala.util.Try$.apply(Try.scala:209)
	at com.programmaticallyspeaking.ncd.infra.ExecutorProxy$Handler.$anonfun$invoke$1(ExecutorProxy.scala:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by provegard** [comment]
Fixed with 1f0c6b157f7521f45ca0efe007eb4843b4b6e9ff
