### ISSUE TITLE
Fix VSCode instructions

### ISSUE THREAD

**Issue by provegard** [provegard/ncdbg#79]
The text about launch.json is unclear.

Connection fails, error in log:

File request outside base URL (http://localhost:7778/files): http://localhost:7778/json/list

**Comment by provegard** [comment]
More VSCode problems:

## 1

VSCode wants to know the user agent:

    Evaluation of '(function(){return (navigator.userAgent);}).call(null);' for stack frame $top cannot be done in a non-paused state.

Not responding to it doesn't seem to be a problem though.

## 2

The Local varaibles entry doesn't work (spinning indicator). Exception in NCDbg:

```
java.lang.NullPointerException: null
	at com.programmaticallyspeaking.ncd.chrome.domains.ScriptEvaluateSupport$.serializeArgumentValues(ScriptEvaluateSupport.scala:17)
	at com.programmaticallyspeaking.ncd.chrome.domains.Runtime$$anonfun$handle$1.applyOrElse(Runtime.scala:221)
	at com.programmaticallyspeaking.ncd.chrome.domains.DomainActor.$anonfun$processRequest$2(DomainActor.scala:148)
	at scala.util.Try$.apply(Try.scala:209)
	at com.programmaticallyspeaking.ncd.chrome.domains.DomainActor.com$programmaticallyspeaking$ncd$chrome$domains$DomainActor$$processRequest(DomainActor.scala:148)
	at com.programmaticallyspeaking.ncd.chrome.domains.DomainActor$$anonfun$receiveEnabled$1.applyOrElse(DomainActor.scala:96)
	at akka.actor.Actor.aroundReceive(Actor.scala:497)
	at akka.actor.Actor.aroundReceive$(Actor.scala:495)
	at com.programmaticallyspeaking.ncd.chrome.domains.DomainActor.aroundReceive(DomainActor.scala:22)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
