### ISSUE TITLE
Exception on startup

### ISSUE THREAD

**Issue by benoitcerrina** [provegard/ncdbg#88]
not really a big deal and it could be closed as a restriction, however whenever I start the debugger I have an immediate exception stack:
Failed to handle event com.sun.tools.jdi.EventSetImpl$VMStartEventImpl
java.lang.NullPointerException: null
        at com.programmaticallyspeaking.ncd.nashorn.JDIExtensions$ExtEvent.handle(JDIExtensions.scala:24)
        at com.programmaticallyspeaking.ncd.nashorn.NashornDebuggerHost.$anonfun$handleOperation$1(NashornDebuggerHost.scala:310)
        at com.programmaticallyspeaking.ncd.nashorn.NashornDebuggerHost.$anonfun$handleOperation$1$adapted(NashornDebuggerHost.scala:307)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at com.programmaticallyspeaking.ncd.nashorn.NashornDebuggerHost.handleOperation(NashornDebuggerHost.scala:307)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.programmaticallyspeaking.ncd.infra.ExecutorProxy$Handler.$anonfun$invoke$3(ExecutorProxy.scala:42)
        at scala.util.Try$.apply(Try.scala:209)
        at com.programmaticallyspeaking.ncd.infra.ExecutorProxy$Handler.$anonfun$invoke$2(ExecutorProxy.scala:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

It doesn't look to good and should probably be caught and reported a little less abruptly

**Comment by provegard** [comment]
I have never seen this, but I added an extra safeguard against an event request that is `null`. Let me know if it works for you, re-open if it doesn't (GitHub auto-closed the issue).

**Comment by benoitcerrina** [comment]
it is fixed but I now have a compilation warning:
E:\dev\ncdbg\src\main\scala\com\programmaticallyspeaking\ncd\nashorn\JDIExtensions.scala:26: non-variable type argument com.sun.jdi.event.Event in type pattern
com.sun.jdi.event.Event => Boolean (the underlying of com.programmaticallyspeaking.ncd.nashorn.NashornDebuggerHost.EventHandler) is unchecked since it is elimin
ated by erasure
        case h: EventHandler => h(event)
                ^
one warning found



Otherwise the startup traces with the fix look like this which seems fine to me:

NCDbg version: 0.6.0-95-ga50e471.dirty
Local Java version: 1.8.0_144
Connecting to localhost:8000...
Connected!
Remote VM information:
- Java Debug Interface (Reference Implementation) version 1.8
- Java Debug Wire Protocol (Reference Implementation) version 1.8
- JVM Debug Interface version 1.2
- JVM version 1.8.0_131 (Java HotSpot(TM) 64-Bit Server VM, mixed mode, sharing)
Enabling breaking on exceptions in script classes.
Server is listening on localhost:7778
Open this URL in Chrome: chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=localhost:7778/dbg
Receiving WebSocket clients at localhost/127.0.0.1:7778
Class scanning complete!
New WebSocket client from /127.0.0.1:54319 at endpoint '/dbg'.
A Developer Tools client connected!
Enabling domain Profiler
Failed to handle message: Cannot create domain method Debugger.setAsyncCallStackDepth because the domain and/or method are unknown
Failed to handle message: Cannot create domain method Debugger.setBlackboxPatterns because the domain and/or method are unknown
Enabling domain Runtime
Enabling domain Debugger
Enabling automatic breaking at JavaScript 'debugger' statements
Host initialization is complete.
Enabling debugging, sending all parsed scripts to the client.
Will pause on breakpoints
No line locations available for jdk.nashorn.internal.scripts.Script$121$\^eval\_
Setting an unresolved breakpoint with ID ndb1 at line 1326 in script with URL xplantest/SchedulerTest
Setting an unresolved breakpoint with ID ndb2 at line 1037 in script with URL xplan/xPlanDSLCCommandImplementation
Setting an unresolved breakpoint with ID ndb3 at line 1014 in script with URL xplan/xPlanDSLCCommandImplementation
Setting an unresolved breakpoint with ID ndb4 at line 4 in script with URL xplantest/XPlanServerTests
Setting an unresolved breakpoint with ID ndb5 at line 1325 in script with URL xplantest/XPlanServerTests
Setting an unresolved breakpoint with ID ndb6 at line 327 in script with URL xplantest/XPlanServerTests
Setting an unresolved breakpoint with ID ndb7 at line 375 in script with URL xplantest/XPlanServerTests
Resolving breakpoint ndb4 with location 4:5 in script nds275
<==========---> 83% EXECUTING [2m 43s]
> :run

**Comment by provegard** [comment]
Yed, I know there are some warnings, but they shouldn't matter. I don't know of any Scala mechanism for disabling individual warnings.
